config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'gallery/index'
  get 'gallery/search'
    get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/purchase_complete'
  resources :stores
  get 'admin/login'
  post 'admin/login'
  get "/users/admin/login"
  get 'admin/logout'
  post 'gallery/search'
  devise_for :users
  
  get 'home/index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items,:dependent => :destroy
	def add_product(store_id)
		current_item=line_items.find_by_store_id(store_id)
		if current_item
			current_item.quantity+=1
		else
			current_item=line_items.build(:store_id=>store_id)
		end
		current_item
	end
	def total_price
		line_items.to_a.sum{|item| item.total_price}
		
	end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
    begin
    @cart=Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    logger.error "invalid access for cart #{params[:id]}"
    redirect_to @cart,:notice => "invalid cart"
    else
      respond_to do |format|
        format.html
      end
    end
  end
  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% unless cart.line_items.empty? %>
<h3>Your Cart</h3>
<style>


#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 80%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}
</style>



<table id="customers">

	<tr>
		<th>Quanitity</th>
		<th>product</th>
		<th>Amount</th>
		
	</tr>
	<%= render(cart.line_items) %>
	<tr>
		<td colspan="2">Total</td>
		<td class="total_cell"><%= number_to_currency(cart.total_price)  %></td>
	</tr>
</table></br>
<% session[:amount] = cart.total_price %> 
<%= button_to 'Empty Cart', cart, :method => :delete, :confirm => 'Are you sure?' , :class=>"btn btn-warning btn-sm"%>
<p></br>
	<div class="king3">
	<%= link_to "Continue Shopping",:controller=>"gallery",:action=>"index"%> </div>&nbsp&nbsp|&nbsp&nbsp 
	<% if user_signed_in? %><div class="king3">
	<%= link_to "Checkout" ,:controller=>"gallery",:action=>"checkout" %>
		<% else %><div class="king3">
		<%= link_to "Checkout",new_user_session_path,:controller=>"admin",:action=>"login" %></div>
		<% end %>
	</p>
<% end %>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>